version: "0.1" 
services:
  mysql: 
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=database_development"
      - "TZ=Asia/Shanghai"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - 3306:3306
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000
      KAFKA_ADVERTISED_HOST_NAME: ${hostIP}
      KAFKA_ZOOKEEPER_CONNECT: ${hostIP}:2181
    depends_on:
      - zookeeper
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
  redis: 
    image: redis:3.2
    ports: 
      - "6379:6379"